[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo='neoclide/coc.nvim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo='cespare/vim-toml'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'Rigellute/shades-of-purple.vim'

[[plugins]]
repo = 'itchyny/landscape.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
source ~/.vim/config/plugins/vim-airline.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Shougo/vimproc'
hook_post_update = '''
source ~/.vim/config/plugins/vimproc.vim
'''

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = '''
source ~/.vim/config/plugins/vimtex.vim
'''

