[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo='cespare/vim-toml'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'itchyny/landscape.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
source ~/.vim/config/plugins/vim-fugitive.vim
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.vim/config/plugins/lightline.vim
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/vimproc'
hook_post_update = '''
source ~/.vim/config/plugins/vimproc.vim
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'

