#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
# Customize to your needs...
alias ls="colorls --sd"
alias la="ls -lA"
alias "airport=/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"
setopt auto_cd
function chpwd() { ls }
#LS_COLORS=~/dotfiles/material-design-colors.itermcolors
LS_COLORS=~/gochiusa/gochiusa.dircolors
